### PR TITLE
feat: added support for ocp v4.16 

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

Refer Issue: [Issue-10665](https://github.ibm.com/GoldenEye/issues/issues/10665)

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

* Support added to include ocp version 4.16 

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by imprateeksh** [comment]
The tests are failing as it references the `base-ocp-vpc` module where the change related to version 4.16 is not yet merged.

**Comment by ocofaigh** [comment]
@imprateeksh Base OCP is merged. Please update to use https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/releases/tag/v3.32.0

**Comment by imprateeksh** [comment]
looking into pr failure

**Comment by imprateeksh** [comment]
The upgrade test is now [failing](https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/actions/runs/11113117734/job/30876875113#step:7:4539) due to the change in add on version. 
Addon `cluster-auto-scaler` version `1.2.1` is [supported](https://cloud.ibm.com/docs/containers?topic=containers-supported-cluster-addon-versions#cluster-autoscaler-1.2.1) for `ocp v4.16` , this value is [currently](https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/blob/f24b18f4ba8c5ee9f6b3f72f2ea184c1c0b53fc9/examples/end-to-end-example/main.tf#L209) set to `1.2.0`

Hence the upgrade test can be skipped.

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
