### PR TITLE
fix: expose verify_worker_network_readiness

### PR DESCRIPTION
**Pull request by dishankkalra23**
### Description

Issues addressed by this PR

https://github.ibm.com/GoldenEye/issues/issues/4720

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
@dishankkalra23 pipeline should be unblocked now - can you please resolve conflicts?

**Comment by dishankkalra23** [comment]
@ocofaigh Can you please check if this PR is ready to be merged?

**Pull request merged**
