### PR TITLE
fix: renovate pr versions

### PR DESCRIPTION
**Pull request by jor2**
### Description

fix renovate pr, not updated to latest versions which caused issue. upgrading fixes https://ibm-cloudplatform.slack.com/archives/CG06FQ31P/p1717494909362029?thread_ts=1717484141.448119&cid=CG06FQ31P

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content
Upgrade modules to latest versions that support tf version `1.7`.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by jor2** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/pull/251

**Comment by jor2** [comment]
Skipped upgrade tests as it was [failing](https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/actions/runs/9373797376/job/25808573023#step:7:1575) due to version constraints relating to `1.7.0` upper limit change introduced.

**Review by ocofaigh — APPROVED** [review]

**Comment by ocofaigh** [comment]
@jor2 If you didn't update common-dev-assets in this PR, you wouldnt of needed to skip the upgeade test. The new version of common-dev-assets had the updated terraform version. The idea was that we would merge this Pr first, and then update common-dev-assets in https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive/pull/266 after. I went ahead and merged anyway as the risk is low, but I don't suggest updating common-dev-assets as part of PRs you create and instead allow renovate to update it (unless of course you need a newer version of it for your PR to pass)

**Pull request merged**
