### PR TITLE
fix: remove support for latest ocp

### PR DESCRIPTION
**Pull request by shemau**
### Description

Remove support for `latest` as an option for OCP version.

Issue: 6906

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by shemau** [comment]
Blocked by iks-config-map error

**Comment by ocofaigh** [comment]
@shemau Can you update to base OCP version `v3.16.0` in this PR?

**Comment by shemau** [comment]
Upgrade test shows a known issue

```hcl
Error: The ConfigMap "iks-ca-configmap" does not exist
```

Unfortunately this is during the main branch deploy before the upgrade step. This is fixed in base 3.16.0 as part of this PR, but that is too late for the upgrade to run.

I will add a SKIP UPGRADE TEST commit

**Comment by ocofaigh** [comment]
@Aashiq-J FYI, it even failed after 40 attempts! `2024-02-08T21:30:47.2686909Z TestRunCompleteExample/4.14 2024-02-08T21:30:47Z logger.go:66: [0m[1mmodule.ocp_all_inclusive.module.ocp_base.null_resource.config_map_status[0] (local-exec):[0m [0mConfigMap 'iks-ca-configmap' did not become available within 40 attempts.`

I'll retry this PR, but we need to contact IKS I think to see why it takes so long now

**Comment by ocofaigh** [comment]
```
Error: [0m Error: [ERROR] Error downloading the cluster config [cn2vbsuw00884e4d7bmg]: Request failed with status code: 401, ServerErrorResponse: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

Known issue - I might have a fix. If it works, Ill push to this PR

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
